export class Employee {
    'name': String;
    'address': String;
    'postalCode': String;
    'location': String;
    'email': String;
    'phoneNumber': Number;
    'academicQualifications': String;
    'academicInstitution': String;
    'course': String;
    'cc': Number;
    'ccValidity': Date;
    'nationality': String;
    'birthDate': Date;
    'nif': String;
    'niss': String;
    'maritalStatus': String;
    'maritalWorkStatus': Boolean;
    'dependents': Number;
    'dependentsAges': String;
    'iban': String;
    'swift': String;
    'professionalCategory': String
    'specialTech': String;
    'otherTech': String;
    'admissionDate': Date;
    'grossSalary': Number;
    'contractType': String;
    'extras': String;
    'twelfths': Boolean;
    'twelfths5050': Boolean;
    'twelfths112': Boolean;
    'foodAllowance': Boolean;
    'workSchedule': String;
    'sports': Boolean;
    'sportsType': String;
    'otherActivities': String;
    'suggestedActivities': String;
    'hobbies': String;
    'otherInterests': String;
    'client': String;
    'clientSector': String;
    'project': String;
    'fare': String;
    'healthInsurance': String;
    'companyFinancing': String;
    'extensible': String;
    'insuranceRelativeName': String;
    'insuranceRelativeBirthDate': String;
    'companyFinancingRelative': String;
    'commentarySection': String;
    constructor(data?: any) {
        Object.assign(this, data);
    }
}
